FINI-448: Utility scripts SQL auth
Lombiq/Utility-Scripts pull request #5
Opened 2021-03-15 15:43 UTC by DAud-IcI

2021-04-05 22:49 UTC, Piedone requested changes

2021-04-05 22:49 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +   Creates a new Sql Server connection object.
```suggestion
   Creates a new SQL Server connection object.
```

2021-04-05 22:49 UTC, Piedone commented on SqlServer/Import-BacpacToSqlServer/Import-BacpacToSqlServer.psm1
> +        [Parameter(HelpMessage = "The user name of the SQL Server instance that will host the imported database.")]
Mármint egy master DB useré? Mert SQL Server instance-nek, mint olyannak, nincs usere.

2021-04-05 22:49 UTC, Piedone commented on SqlServer/New-SqlServerDatabase/New-SqlServerDatabase.psm1
> -        }
Ez az ellenőrzés továbbra is kellene.

2021-04-05 22:49 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
not gud
![image](https://user-images.githubusercontent.com/1976647/113625787-a8a03d80-9661-11eb-86da-d70d827af528.png)

2021-04-05 23:36 UTC, DAud-IcI commented on SqlServer/New-SqlServerDatabase/New-SqlServerDatabase.psm1
> -        }
Fölösleges, mert ugyanez ott van a két sorral lejjebbi `Test-SqlServerDatabase` és a kettő között levő `New-SqlServerConnection` magában nem fog hibát dobni ha nem létezik az adatbázis, csak ha elkezdenéd használni.

2021-04-06 09:35 UTC, Piedone commented on SqlServer/New-SqlServerDatabase/New-SqlServerDatabase.psm1
> -        }
OK

2021-04-07 19:12 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Ugyanaz: 
![image](https://user-images.githubusercontent.com/1976647/113921188-fa71d080-97e5-11eb-9b0d-f21d02d12dfa.png)

2021-04-07 19:14 UTC, Piedone requested changes
Lásd error feljebb.

2021-04-07 19:28 UTC, DAud-IcI commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Nem ugyanaz, most már eljutott az OC futtatásig. (akkor elvileg a powershell-es rész rendben van) El tudod küldeni a log fájlt?

2021-04-07 19:38 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Ja igen, így teljes:

![image](https://user-images.githubusercontent.com/1976647/113923854-54c06080-97e9-11eb-9a80-f18c5eb1adc5.png)

Tehát első futásra assembly error van, másodikra az adott script window-ban már nincs. Stabil repro.

De másodikra valóban még setup error is van:
[orchard-log-2021-04-07.log](https://github.com/Lombiq/Utility-Scripts/files/6274045/orchard-log-2021-04-07.log)

2021-04-08 11:26 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Setup error továbbra is van:
[orchard-log-2021-04-08.log](https://github.com/Lombiq/Utility-Scripts/files/6278184/orchard-log-2021-04-08.log)

2021-04-08 11:31 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Illetve ez elrontotta a Import-BacpacToSqlServer scriptet: ezzel BACPAC DB exportokat tudsz importálni a local SQL Serverbe. Ha a mappájában lévő registry fájlt is importálod, akkor egy .bacpack-ra jobb klikk -> Import to SQL Server with PowerShell, vagy dupla klikk is importálja. Most viszont ez így fog megakadni, amennyiben az adott DB nem létezett korábban:

![image](https://user-images.githubusercontent.com/1976647/114019205-6730ad80-986e-11eb-93a8-86ed50eff85c.png)

2021-04-08 12:27 UTC, DAud-IcI commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Milyen paraméterrel indítottad? A setup error gyanús, hogy [sql authentication-t próbál olyan szerveren ahol ez nincs bekapcsolva](https://stackoverflow.com/questions/27267658/no-process-is-on-the-other-end-of-the-pipe-sql-server-2012).

Az `Import-BacpacToSqlServer`-et visszaállítottam dev-re.

2021-04-08 12:38 UTC, Piedone commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Az Import-BacpacToSqlServer nekem továbbra is ugyanazt adja:

![image](https://user-images.githubusercontent.com/1976647/114027077-4caf0200-9877-11eb-895b-4a34f744845a.png)

A resetet nem paramétereztem át, úgy futtatom, ahogy by default a repóban van, ahogy eddig is:
![image](https://user-images.githubusercontent.com/1976647/114027781-073f0480-9878-11eb-8918-77033bd08ead.png)

Viszont a hibaüzenetben ez van benne: "provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe." Nekem ugyan a Shared Memory és Named Pipes protocol is be van kapcsolva SQL Serverben, de ennek a TCP/IP-t kellene inkább használnia.

2021-04-08 17:55 UTC, DAud-IcI commented on SqlServer/New-SqlServerConnection/New-SqlServerConnection.psm1
> +            New-Object ("Microsoft.SqlServer.Management.Common.ServerConnection") $ServerName, $UserName, $Password
Abban nem voltam biztos, hogy melyik auth nem működik. Most megpróbáltam SQL Server Express-el (csak hozzáírtam a `Reset-AppWithSqlServer.ps1`-hez, hogy `-SetupDatabaseServerName ".\SQLEXPRESS"`). Érdekes módon először nekem is dobta az 500 errorokat, aztán meghívtam a `ReloadEveryModuleInPSModulePaths.ps1`-t és elmúlt. 

Az `Import-BacpacToSqlServer`-et megjavítottam, az volt a gond, hogy a `Test-SqlServerDatabase` váratlanul több dolgot is visszatért.

2021-04-08 19:33 UTC, Piedone approved these changes

2021-04-08 21:08 UTC, merged